name: Setup and install
description: Common setup steps for Actions

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 9.9.0

    - uses: actions/setup-node@v4
      with:
        cache: 'pnpm'
        node-version-file: '.nvmrc'

    - shell: bash
      run: pnpm install
